[package]
name = "roblox-offset"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poggers = {git = "https://github.com/pozm/poggers.git"}